=== arctrong/md2html/java/src/main/resources/args_file_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "options": {
            "type": "object",
            "properties": {
                "verbose": { "type": "boolean" },
                "legacy-mode": { "type": "boolean" }
            }
        },
        "default": {
            "type": "object",
            "properties": {
                "template": { "type": "string" },
                "verbose": { "type": "boolean" },
                "input": { "type": "string" },
                "output": { "type": "string" },
                "title": { "type": "string" },
                "no-css": { "type": "boolean" },
                "link-css": { "type": "array", "items": { "type": "string" } },
                "include-css": { "type": "array", "items": { "type": "string" } },
                "page-flows": { "type": "array", "items": { "type": "string" } }
            }
        },
        "documents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "input": { "type": "string" },
                    "output": { "type": "string" },
                    "title": { "type": "string" },
                    "template": { "type": "string" },
                    "link-css": { "type": "array", "items": { "type": "string" } },
                    "include-css": { "type": "array", "items": { "type": "string" } },
                    "no-css": { "type": "boolean" },
                    "add-link-css": { "type": "array", "items": { "type": "string" } },
                    "add-include-css": { "type": "array", "items": { "type": "string" } },
                    "page-flows": { "type": "array", "items": { "type": "string" } },
                    "add-page-flows": { "type": "array", "items": { "type": "string" } },
                    "verbose": { "type": "boolean" }
                }
            }
        },
        "plugins": { "type": "object" }
    },
    "required": [ "documents"]
}

=== arctrong/md2html/test/test_input/ReplacePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/ReplacePluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/content.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "ReplacePlugin" }
    ],
    "plugins": {
        "page-variables": {},
        "replace": [
            { "markers": ["replace1", "replace2"], "replace-with": "pref1+${1}+suff1" },
            { "markers": ["replace3", "replace4"], "replace-with": "pref2+${1}+middle2+${2}+suff2" }
        ]
    }
}

=== arctrong/md2html/test/test_input/PageFlowsPlugin/md2html_args_old_syntax.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/PageFlowsPlugin/template_old_syntax.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        {"input": "page1.txt", "title": "Page 1", "page-flows": ["page_flow_1"]},
        {"input": "page2.txt", "title": "Page 2", "page-flows": ["page_flow_2"]},
        {"input": "page3.txt", "title": "Page 3", "page-flows": ["page_flow_1", "page_flow_2"]}
    ],
    "plugins": {
        "page-flows": {
            "page_flow_2": [],      
            "page_flow_1": [
                {"link": "https://www.google.com/", "title": "Google", "external": true}
            ],
            "page_flow_3": [
                {"link": "https://en.wikipedia.org/", "title": "Wikipedia", "external": true,
                    "custom_string": "custom string value", "custom_number": 101.4, 
                    "custom_boolean": true}
            ]
        }
    }
}

=== arctrong/md2html/test/test_input/IndexPluginTest/md2html_args_several.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IndexPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/styles.css"]
    },
    "documents": [
        { "input": "several_indexes_1.txt", "title": "Page 1", "page-flows": ["page_flow_1"] },
        { "input": "several_indexes_2.txt", "title": "Page 2", "page-flows": ["page_flow_1"] }
    ],
    "plugins": {
        "page-flows": {},
        "variables": {"custom_variable_1": "custom value 1" },
        "index": {"index1": {"output": "index_page_1.html", "title": "Index 1", "page-flows": ["page_flow_1"],
                             "index-cache": "index_cache_1.json", "index-cache-relative": true },
                  "index2": {"output": "index_page_2.html", "title": "Index 2", "page-flows": ["page_flow_1"],
                             "index-cache": "index_cache_2.json", "index-cache-relative": true } 
                 }
    }
}

=== arctrong/md2html/test/test_input/IncludeFilePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IncludeFilePluginTest/page_template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "IncludeFilePlugin test" }
    ],
    "plugins": {
        "include-file": [
            { "markers": ["include_java"], "root-dir": "test_input/IncludeFilePluginTest/code/java/" },
            { "markers": ["include_shell"], "root-dir": "test_input/IncludeFilePluginTest/code/shell/", "trim": false },
            { "markers": ["include_code1", "include_code2"], "root-dir": "test_input/IncludeFilePluginTest/code/" }
        ]
    }
}

=== arctrong/md2html/test/test_input/PageLinksPluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/PageLinksPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1_single.txt", "title": "Page 1" },
        { "input": "page2_single.txt", "title": "Page 2", "code": "page02" },
        { "input-glob": "subdir/*.txt", "title-from-variable": "title", "code-from-variable": "code" }
    ],
    "plugins": {
        "page-variables": {},
        "page-links": {}
    }
}

=== arctrong/md2html/test/test_input/RelativePathsPluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/RelativePathsPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "Page 1 - relative-paths" },
        { "input-glob": "subdir/*.txt", "title-from-variable": "title" }
    ],
    "plugins": {
        "page-variables": {},
        "relative-paths": { 
            "markers": ["p1", "p2"],
            "paths": { 
                "pict1": "test_input/RelativePathsPluginTest/pict1/",
                "pict2": "test_input/RelativePathsPluginTest/pict2/",
                "subdir": "test_input/RelativePathsPluginTest/subdir/"
            }
         }
    }
}

=== arctrong/md2html/test/test_input/WrapCodePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/WrapCodePluginTest/page_template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "Page 1" }
    ],
    "plugins": {
        "page-variables": {},
        "wrap-code": {
            "wrap_java": {"style": "code",
                "template": "test_input/WrapCodePluginTest/code_template.html", "variables": {"noPageTitle": true}},
            "wrap_shell": {"style": "shell", 
                "template": "test_input/WrapCodePluginTest/code_template.html", "variables": {"noPageTitle": true}}
        }
    }
}

=== arctrong/md2html/test/test_input/PageFlowsPlugin/md2html_args_new_syntax.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/PageFlowsPlugin/template_new_syntax.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        {"input": "page1.txt", "output": "new_syntax/page1.html", "title": "Page 1", 
            "page-flows": ["page_flow_1"]},
        {"input": "page2.txt", "output": "new_syntax/page2.html", "title": "Page 2", 
            "page-flows": ["page_flow_2"]},
        {"input": "page3.txt", "output": "new_syntax/page3.html", "title": "Page 3", 
            "page-flows": ["page_flow_1", "page_flow_2"]}
    ],
    "plugins": {
        "page-flows": {
            "page_flow_1": {"groups": ["group1"]},
            "page_flow_2": { "title": "Page flow 2", "groups": ["group1"], "items": [
                {"link": "https://www.google.com/", "title": "Google", "external": true}
            ]},
            "page_flow_3": { "title": "Page flow 3", "groups": ["group1"], "items": [
                {"link": "https://en.wikipedia.org/", "title": "Wikipedia", "external": true,
                    "custom_string": "custom string value", "custom_number": 101.4, 
                    "custom_boolean": true}
            ]}
        }
    }
}
