=== arctrong/md2html/java/src/main/resources/args_file_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "options": {
            "type": "object",
            "properties": {
                "verbose": { "type": "boolean" },
                "legacy-mode": { "type": "boolean" }
            }
        },
        "default": {
            "type": "object",
            "properties": {
                "template": { "type": "string" },
                "verbose": { "type": "boolean" },
                "input": { "type": "string" },
                "output": { "type": "string" },
                "title": { "type": "string" },
                "no-css": { "type": "boolean" },
                "link-css": { "type": "array", "items": { "type": "string" } },
                "include-css": { "type": "array", "items": { "type": "string" } },
                "page-flows": { "type": "array", "items": { "type": "string" } }
            }
        },
        "documents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "input": { "type": "string" },
                    "output": { "type": "string" },
                    "title": { "type": "string" },
                    "template": { "type": "string" },
                    "link-css": { "type": "array", "items": { "type": "string" } },
                    "include-css": { "type": "array", "items": { "type": "string" } },
                    "no-css": { "type": "boolean" },
                    "add-link-css": { "type": "array", "items": { "type": "string" } },
                    "add-include-css": { "type": "array", "items": { "type": "string" } },
                    "page-flows": { "type": "array", "items": { "type": "string" } },
                    "add-page-flows": { "type": "array", "items": { "type": "string" } },
                    "verbose": { "type": "boolean" }
                }
            }
        },
        "plugins": { "type": "object" }
    },
    "required": [ "documents"]
}

=== arctrong/md2html/test/test_input/GlobInputTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/GlobInputTest/template.html",
        "verbose": false
    },
    "documents": [
        { "input": "single_doc.txt", "title": "Single document", "page-flows": ["all_pages"] },
        { "input-glob": "subdir01/**/*.txt", "page-flows": ["all_pages", "subdir01"], "title-from-variable": "title", "sort-by-file-name": true },
        { "input-glob": "subdir02/*.txt", "page-flows": ["all_pages", "subdir02"], "title-from-variable": "title", "sort-by-variable": "SORT_ORDER" },
        { "input-glob": "subdir03/*.txt", "page-flows": ["all_pages", "subdir03"], "title-from-variable": "title", "sort-by-title": true }

    ],
    "plugins": {
        "relative-paths": { "resource_path": "../doc/" },
        "page-flows": {},
        "page-variables": {}
    }
}

=== arctrong/md2html/bin/new_project/md2html_args.json
{
    "options": {
        "verbose": true
    },
    "default": {
        "input-root": "doc_src",
        "output-root": "doc/content",
        "template": "doc_src/templates/multipage.html",
        "no-css": true,
        "verbose": true
    },
    "documents": [
        { "input-root": "", "output-root": "", "input": "readme.txt", "title": "Home", 
            "page-flows": ["sections", "nav"] },
        { "input-glob": "sections/*.txt", "page-flows": ["sections", "nav"], 
            "title-from-variable": "title", "code-from-variable": "code", 
            "sort-by-variable": "SORT_ORDER" }
    ],
    "plugins": {
        "variables": {
            "html_lang": "en",
            "show_source_link": true,
            "theme": "light"
        },
        "page-variables": {},
        "relative-paths": {
            "markers": ["path"],
            "paths": {
                "resource_path": "doc/",
                "pict": "doc/pict/"
            }
        },
        "page-flows": {
            "header": [
                { "link": "readme.html", "title": "", "image": "favicon.png", "image_class": "logo_image",
                    "image_alt": "Logo" },
                { "link": "readme.html", "title": "Home", "class": "toggle_wide_only_inline" },
                { "link": "doc/content/index_page.html", "title": "Index", "class": "toggle_wide_only_inline" },
                { "link": "doc/content/index_page.html", "title": "", "class": "toggle_narrow_only_inline",
                    "image": "layout/pict/search.png", "image_class": "header_image index_image",
                    "image_alt": "Index" }
            ],
            "header_wide_only": [
                { "link": "https://add.your/link/here", "title": "GitHub", "external": true }
            ],
            "sections": { "groups": ["sidebar"] },
            "useful_links": { "title": "Useful links", "groups": ["sidebar"], "items": [
                { "link": "https://daringfireball.net/projects/markdown/", "title": "Markdown", "external": true },
                { "link": "https://github.com/arctrong/md2html", "title": "md2html", "external": true }
            ]}
        },
        "index": {"index": {"output": "index_page.html", "title": "Index", "index-cache": "index_cache.json", 
                    "index-cache-relative": true, "letters": true, "letters-block": true,
                    "add-link-css": ["doc/layout/index.css"] }
        },
        "page-links": { "markers": ["page"] }
    }
}

=== arctrong/md2html/test/test_input/IgnorePluginTest/md2html_args.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IgnorePluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/layout/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "IgnorePlugin" },
        { "input": "page2.txt", "title": "IgnorePlugin2", "code": "page2" }
    ],
    "plugins": {
        "page-variables": {},
        "page-links": {},
        "ignore": {}
    }
}

=== arctrong/md2html/test/test_input/IndexPluginTest/md2html_args_partial.json
{
    "options": {
        "verbose": false
    },
    "default": {
        "template": "test_input/IndexPluginTest/template.html",
        "verbose": false,
        "link-css": ["../doc/styles.css"]
    },
    "documents": [
        { "input": "page1.txt", "title": "Page 1" },
        { "input": "page2.txt", "title": "Page 2" },
        { "input": "page3.txt", "title": "Page 3" }
    ],
    "plugins": {
       "variables": {"custom_variable_1": "custom value 1" },
        "index": {"output": "index_page.html", "title": "Index",
            "index-cache": "index_cache.json", "index-cache-relative": true }
    }
}
